import { relations, sql } from "drizzle-orm";
import {
  boolean,
  index,
  integer,
  pgTable,
  jsonb,
  serial,
  text,
  timestamp,
} from "drizzle-orm/pg-core";

export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  passwordHash: text("password_hash").notNull(),
  shopName: text("shop_name").notNull().default("My Kitchen"),
  currency: text("currency").notNull().default("Rs"),
  /** ISO country code (PK, US, GB, ...) picked at signup; drives the default currency. */
  country: text("country").notNull().default("PK"),
  language: text("language").notNull().default("en"),
  /** "owner" = shop owner customer, "admin" = master admin (you). */
  role: text("role").notNull().default("owner"),
  /** Master admin can suspend a customer without deleting their data. */
  suspended: boolean("suspended").notNull().default(false),
  /** Null = no active subscription yet (must redeem a key). */
  accessExpiresAt: timestamp("access_expires_at", { withTimezone: true }),
  /** Max menu items this shop may list. Master admin can raise it per restaurant. */
  itemLimit: integer("item_limit").notNull().default(500),
  /** Owner option: receipts number orders from 1 each day (daily receipt counter). */
  dailyOrderReset: boolean("daily_order_reset").notNull().default(false),
  /** Opt-in extra features (Settings → Add-ons). Everything off by default. */
  addons: jsonb("addons").notNull().default({}),
  /** Dine-in tables add-on: how many table QR cards to offer. */
  tableCount: integer("table_count").notNull().default(12),
  /** Updated by the app heartbeat; master admin sees the restaurant as Online/Offline. */
  lastSeenAt: timestamp("last_seen_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

/** One-time password reset tokens generated from the "Forgot password" form. */
export const passwordResets = pgTable(
  "password_resets",
  {
    id: serial("id").primaryKey(),
    email: text("email").notNull(),
    token: text("token").notNull().unique(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    usedAt: timestamp("used_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("password_resets_email_idx").on(table.email)],
);

/**
 * Unique activation keys generated by the master admin and sold to shop owners.
 * Redeeming a key extends the owner's `accessExpiresAt`.
 */
export const licenseKeys = pgTable(
  "license_keys",
  {
    id: serial("id").primaryKey(),
    code: text("code").notNull().unique(),
    /** monthly | yearly | custom | lifetime */
    plan: text("plan").notNull().default("monthly"),
    /** Days of access granted on redemption. 36500 for lifetime. */
    durationDays: integer("duration_days").notNull().default(30),
    note: text("note").notNull().default(""),
    revoked: boolean("revoked").notNull().default(false),
    redeemedByUserId: integer("redeemed_by_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    redeemedAt: timestamp("redeemed_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("license_keys_redeemed_idx").on(table.redeemedByUserId)],
);

/**
 * Staff sub-logins created by a shop owner (NOT the master admin).
 * role: "chef" (kitchen display) or "cashier" (point of sale).
 * orders routed by item category go to matching chefs.
 */
export const staff = pgTable(
  "staff",
  {
    id: serial("id").primaryKey(),
    ownerId: integer("owner_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    email: text("email").notNull().unique(),
    passwordHash: text("password_hash").notNull(),
    role: text("role").notNull().default("cashier"),
    /** Categories this chef handles; empty = everything. */
    categories: text("categories").array().notNull().default(sql`'{}'::text[]`),
    active: boolean("active").notNull().default(true),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("staff_owner_idx").on(table.ownerId)],
);

export const menuItems = pgTable(
  "menu_items",
  {
    id: serial("id").primaryKey(),
    userId: integer("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    category: text("category").notNull().default("General"),
    description: text("description").notNull().default(""),
    price: integer("price").notNull().default(0),
    imageData: text("image_data"),
    emoji: text("emoji").notNull().default("🍽️"),
    available: boolean("available").notNull().default(true),
  /** Remaining pieces for the optional stock add-on; null = unlimited. */
  stockQty: integer("stock_qty"),
  /** Optional extras/add-ons for this item: [{ name, price }] (modifiers add-on). */
  extras: jsonb("extras").notNull().default([]),
  /** What this item costs us — feeds the daily-profit add-on. 0 = unknown. */
  costPrice: integer("cost_price").notNull().default(0),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("menu_items_user_idx").on(table.userId)],
);

export const orders = pgTable(
  "orders",
  {
    id: serial("id").primaryKey(),
    userId: integer("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    orderNumber: integer("order_number").notNull(),
    customerName: text("customer_name").notNull().default(""),
    /** Staff member who took the order (null = owner took it). */
    staffId: integer("staff_id").references(() => staff.id, { onDelete: "set null" }),
    takenBy: text("taken_by").notNull().default(""),
    subtotal: integer("subtotal").notNull().default(0),
    total: integer("total").notNull().default(0),
    amountReceived: integer("amount_received").notNull().default(0),
    changeDue: integer("change_due").notNull().default(0),
    itemCount: integer("item_count").notNull().default(0),
  /** Same-day order sequence (PKT day) shown on receipts when the daily counter is enabled. */
  dailyOrderNo: integer("daily_order_no").notNull().default(0),
  /** Checkout discount add-on: percent|flat|none + the applied amount. */
  discountType: text("discount_type").notNull().default("none"),
  discountValue: integer("discount_value").notNull().default(0),
  discountAmount: integer("discount_amount").notNull().default(0),
  /** Payment methods add-on: cash|card|jazzcash|easypaisa|bank. */
  paymentMethod: text("payment_method").notNull().default("cash"),
  /** Void add-on: soft cancel keeping an audit trail (excluded from totals). */
  voidedAt: timestamp("voided_at", { withTimezone: true }),
  voidReason: text("void_reason").notNull().default(""),
  /** Customer WhatsApp add-on: phone in international format for one-tap updates. */
  customerPhone: text("customer_phone").notNull().default(""),
  /** Set when the kitchen marks all items ready/served — used for hourly heatmap & open-order age. */
  completedAt: timestamp("completed_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("orders_user_created_idx").on(table.userId, table.createdAt)],
);

export const orderItems = pgTable(
  "order_items",
  {
    id: serial("id").primaryKey(),
    orderId: integer("order_id")
      .notNull()
      .references(() => orders.id, { onDelete: "cascade" }),
    menuItemId: integer("menu_item_id").references(() => menuItems.id, {
      onDelete: "set null",
    }),
    name: text("name").notNull(),
    unitPrice: integer("unit_price").notNull(),
    quantity: integer("quantity").notNull(),
    lineTotal: integer("line_total").notNull(),
    /** Snapshot of the menu item's category, used for chef routing. */
    category: text("category").notNull().default(""),
  /** Cost price at the time of sale (snapshot for profit reports). */
  costPrice: integer("cost_price").notNull().default(0),
    /** Kitchen progression: new -> preparing -> ready */
    status: text("status").notNull().default("new"),
  },
  (table) => [index("order_items_order_idx").on(table.orderId)],
);

export const usersRelations = relations(users, ({ many }) => ({
  menuItems: many(menuItems),
  orders: many(orders),
  licenseKeys: many(licenseKeys),
  staff: many(staff),
}));

export const staffRelations = relations(staff, ({ one }) => ({
  owner: one(users, { fields: [staff.ownerId], references: [users.id] }),
}));

export const licenseKeysRelations = relations(licenseKeys, ({ one }) => ({
  redeemedBy: one(users, {
    fields: [licenseKeys.redeemedByUserId],
    references: [users.id],
  }),
}));

export const menuItemsRelations = relations(menuItems, ({ one }) => ({
  user: one(users, { fields: [menuItems.userId], references: [users.id] }),
}));

export const ordersRelations = relations(orders, ({ one, many }) => ({
  user: one(users, { fields: [orders.userId], references: [users.id] }),
  staffMember: one(staff, { fields: [orders.staffId], references: [staff.id] }),
  items: many(orderItems),
}));

export const orderItemsRelations = relations(orderItems, ({ one }) => ({
  order: one(orders, { fields: [orderItems.orderId], references: [orders.id] }),
}));

/** Daily shop expenses (Kharcha) — the "Aaj ki Bachat" day-close feature. */
/** Cash-drawer shifts for the cashShift add-on. */
export const shifts = pgTable(
  "shifts",
  {
    id: serial("id").primaryKey(),
    userId: integer("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    openedAt: timestamp("opened_at", { withTimezone: true }).notNull().defaultNow(),
    openingCash: integer("opening_cash").notNull().default(0),
    closedAt: timestamp("closed_at", { withTimezone: true }),
    expectedCash: integer("expected_cash").notNull().default(0),
    countedCash: integer("counted_cash").notNull().default(0),
    difference: integer("difference").notNull().default(0),
    note: text("note").notNull().default(""),
  },
  (table) => [index("shifts_user_open_idx").on(table.userId, table.openedAt)],
);

export const expenses = pgTable(
  "expenses",
  {
    id: serial("id").primaryKey(),
    userId: integer("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    title: text("title").notNull().default(""),
    amount: integer("amount").notNull().default(0),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("expenses_user_created_idx").on(table.userId, table.createdAt)],
);
